#!/usr/bin/env python3
"""CLI entry point for repomap tool."""
import argparse
import os
import sys
from watchdog.observers import Observer
from .watcher import RepomapWatcher

AGENTS_NOTE = """\
# REPOMAP.md — Living Repository Map
# This file is auto-generated by `repomap` and updates on every file change.
# Always read REPOMAP.md at the start of a session for the current codebase
# structure and symbol index. Do NOT treat it as a static snapshot.

"""


def _is_gitignored(root, filename):
    """Return True if filename appears in .gitignore."""
    gitignore_path = os.path.join(root, ".gitignore")
    if not os.path.exists(gitignore_path):
        return False
    with open(gitignore_path, "r") as f:
        for line in f:
            stripped = line.strip()
            if stripped == filename or stripped == f"/{filename}":
                return True
    return False


def _prompt(question, default_yes=True):
    """Prompt the user for y/n, return True for yes."""
    hint = "[Y/n]" if default_yes else "[y/N]"
    try:
        answer = input(f"{question} {hint}: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        return False
    if answer == "":
        return default_yes
    return answer in ("y", "yes")


def startup_checks(root):
    """Run one-time setup recommendations on startup."""

    # ── 1. Gitignore check ────────────────────────────────────────────────
    if not _is_gitignored(root, "REPOMAP.md"):
        print()
        print("[RECOMMEND] REPOMAP.md is not in your .gitignore.")
        print("            It is auto-generated and changes on every save —")
        print("            committing it creates noisy diffs.")
        if _prompt("            Add REPOMAP.md to .gitignore?", default_yes=True):
            gitignore_path = os.path.join(root, ".gitignore")
            with open(gitignore_path, "a") as f:
                f.write("\n# repomap auto-generated file\nREPOMAP.md\n")
            print("            ✓ Added REPOMAP.md to .gitignore")
        print()

    # ── 2. AGENTS.md check ────────────────────────────────────────────────
    agents_path = os.path.join(root, "AGENTS.md")
    agents_exists = os.path.isfile(agents_path)
    repomap_path = os.path.join(root, "REPOMAP.md")

    # Check if we already injected the note (idempotent)
    already_noted = False
    if agents_exists:
        with open(agents_path, "r") as f:
            already_noted = "REPOMAP.md — Living Repository Map" in f.read()

    if not already_noted:
        print("[RECOMMEND] Let agents know that REPOMAP.md is a living doc.")
        print()
        print("            [P] Prepend a 'living doc' note to AGENTS.md")
        print("            [S] Symlink AGENTS.md → REPOMAP.md")
        print("                (replaces AGENTS.md; use only if AGENTS.md does not exist)")
        print("            [N] Skip")
        print()
        try:
            choice = input("            Your choice [P/s/n]: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            choice = "n"

        if choice in ("p", ""):
            # Prepend note to AGENTS.md (create if missing)
            existing = ""
            if agents_exists:
                with open(agents_path, "r") as f:
                    existing = f.read()
            with open(agents_path, "w") as f:
                f.write(AGENTS_NOTE + existing)
            print("            ✓ Note prepended to AGENTS.md")

        elif choice == "s":
            if agents_exists:
                print("            [WARN] AGENTS.md already exists — skipping symlink to avoid data loss.")
                print("                   Delete it manually first if you want a symlink.")
            else:
                os.symlink(repomap_path, agents_path)
                print(f"            ✓ Created symlink: AGENTS.md → REPOMAP.md")
        print()


def main():
    """Main entry point for repomap command."""
    parser = argparse.ArgumentParser(description="Generate and watch an LLM-friendly repo map.")
    parser.add_argument("project_directory", help="Project directory to monitor")
    parser.add_argument(
        "--tokens",
        type=int,
        default=8192,
        help="Maximum repo map token budget (default: 8192)",
    )
    parser.add_argument(
        "--no-setup",
        action="store_true",
        help="Skip startup setup recommendations",
    )
    args = parser.parse_args()

    root = os.path.abspath(args.project_directory)
    if not os.path.isdir(root):
        print(f"Error: '{root}' is not a valid directory")
        sys.exit(1)

    if not args.no_setup:
        startup_checks(root)

    watcher = RepomapWatcher(root, map_tokens=args.tokens)
    observer = Observer()
    observer.schedule(watcher, root, recursive=True)
    observer.start()

    try:
        watcher.run_loop()
    except KeyboardInterrupt:
        print("\nStopping repomap watcher...")
        observer.stop()
    finally:
        watcher.cleanup()
    observer.join()


if __name__ == "__main__":
    main()
